options:
  port:
    type: string
    default: "8888"
    description: "port for znc to listen on"
  admin_user:
    type: string
    default: ""
    description: "Admin username"
  admin_password:
    type: string
    default: ""
    description: "Admin password"
